version: '3.3'

services:
   db:
    image: mysql/mysql-server
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "8306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

   wordpress:
    depends_on:
      - db
    build: .
    ports:
      - "8189:80"
    restart: always
    volumes:
       - ./cocolis-woocommerce:/var/www/html/wp-content/plugins/cocolis-woocommerce
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
    cocolis-woocommerce: {}